# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/rebroadcastr',
                'doc_host': 'https://armstrys.github.io',
                'git_url': 'https://github.com/armstrys/rebroadcastr',
                'lib_path': 'rebroadcastr'},
  'syms': {'rebroadcastr.core': {'rebroadcastr.core.foo': ('core.html#foo', 'rebroadcastr/core.py')}}}
