name: Deploy to GitHub Pages
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: linux-latest
    steps:
       - run: sudo apt-get install -y kwalletmanager
       - uses: fastai/workflows/quarto-ghp@master
