name: Deploy to GitHub Pages
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: macos-latest
    steps:
       - uses: fastai/workflows/quarto-ghp@master
