name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: linux-latest
    steps: 
       - run: sudo apt-get install -y kwalletmanager
       - uses: fastai/workflows/nbdev-ci@master
